[package]
name = "shinigami_cmds"
version = "0.1.0"
edition = "2024_07"

[dependencies]
compiler = { path = "../compiler" }
engine = { path = "../engine" }
utils = { path = "../utils" }

[dev-dependencies]
cairo_test.workspace = true

[scripts]
lint = "scarb fmt"
